        <div class="navbar navbar-default">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/">sudoku24.ru</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li <?if (isset($active) && $active == 'index'):?>class="active"<?endif?>> <a href="/">Главная</a></li>
                            <li <?if (isset($active) && $active == 'about'):?>class="active"<?endif?>> <a href="/about">О программе</a></li>
                            <li <?if (isset($active) && $active == 'feedback'):?>class="active"<?endif?>> <a href="/feedback">Обратная связь | Сообщить об ошибке</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>