<!DOCTYPE html>
<html>
    <head>
        <? if (isset($title)):?>
            <title><?=$title?></title>
        <?endif?>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <? foreach ($this->css as $val): ?>
            <link href="<?=$val?>" rel="stylesheet" type="text/css">
        <? endforeach ?>
        <link href="/assets/public_libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    </head>
    <body>
        <? include TEMPLATES_PATH."general/navbar.phtml" ?>