<? include TEMPLATES_PATH . "sudoku_field.phtml"; ?>

<div class="container">
    <button id="solve_task" class="btn btn-primary" type="button">Решить задачу</button>
    <button id="clear_field_button" class="btn " type="button">Очистить поле</button><br><br>
    <button id="insert_random_task" class="btn" type="button">Вставить случайную задачу</button>
</div>

<div id="prog_bar" style = "position: absolute; left: 430px; top: 180px; width: 40px; height: 40px;"><br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspЖдите...</div>